import logo from "@/assets/images/logo-icon.svg";
import Image from "next/image";
import Link from "next/link";
import React from "react";

const Footer = () => {
  const currentYear = new Date().getFullYear();

  return (
    /* <!-- Footer --> */
    <footer className="py-4 mt-24 bg-gray-200">
      <div className="container flex flex-col items-center justify-between gap-2 px-4 mx-auto md:flex-row">
        <div className="flex items-center mb-2 md:mb-0">
          <Image src={logo} alt="Logo" className="w-auto h-10" />
          <span className="ml-2 text-gray-500">レントファインダー</span>
        </div>
        <div>
          <p className="text-sm text-center text-gray-500 md:mt-0">
            *rent data are generated by AI and are used for development purposes
            only.
          </p>
        </div>
        <div>
          <p className="mt-2 text-sm text-gray-500 md:mt-0">
            &copy; {currentYear} RentFinder. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
